const state={battery:false,switch:false,lamp:false,on:false};
const statusEl=document.querySelector('#status'), test=document.querySelector('#test'), score=document.querySelector('#score');
const pieces=document.querySelectorAll('.part');
function setStatus(text){statusEl.textContent=text}
function place(kind){state[kind]=true;document.querySelector(`[data-part="${kind}"]`).classList.add('selected');document.querySelector(`#placed-${kind}`).classList.remove('hidden');document.querySelector(`.slot[data-slot="${kind}"]`).style.display='none';
 if(Object.values(state).slice(0,3).every(Boolean)){test.disabled=false;setStatus('Todo listo: cerrá el interruptor y probá el circuito ⚡')}else setStatus('Seguí colocando las piezas...')}
pieces.forEach(p=>p.addEventListener('click',()=>place(p.dataset.part)));
document.querySelector('#placed-switch .switch-toggle').addEventListener('click',()=>{if(!state.switch)return;state.on=!state.on;document.querySelector('.switch-toggle').classList.toggle('on',state.on);document.querySelector('.switch-toggle').textContent=state.on?'—':'╱';if(state.on)setStatus('Interruptor cerrado. ¡Ahora probalo!');else setStatus('Interruptor abierto')});
test.addEventListener('click',()=>{const good=state.battery&&state.switch&&state.lamp&&state.on;document.querySelectorAll('#wires path').forEach(x=>x.classList.toggle('live',good));document.querySelector('.bulb').classList.toggle('on',good);if(good){score.textContent='100';setStatus('¡Circuito completo! La lámpara está encendida 🎉');show('<div style="font-size:45px">💡</div><h2>¡Lo lograste!</h2><p>Armaste un circuito cerrado: la corriente salió de la batería, pasó por el interruptor y encendió la lámpara.</p><button class="primary" onclick="closeModal()">Seguir jugando</button>')}else{setStatus('Todavía no funciona: revisá el interruptor y las conexiones');show('<div style="font-size:45px">🔎</div><h2>Casi...</h2><p>Para que funcione, todas las piezas deben estar colocadas y el interruptor tiene que estar cerrado.</p>')}});
document.querySelector('#reset').addEventListener('click',()=>location.reload());
document.querySelector('#help').addEventListener('click',()=>show('<div style="font-size:40px">🎮</div><h2>¿Cómo se juega?</h2><p>Elegí las tres piezas de la derecha. Después activá el interruptor y tocá <b>Probar circuito</b>. Un circuito cerrado permite que la corriente vuelva a la batería.</p>'));
function show(html){document.querySelector('#modal-content').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}function closeModal(){document.querySelector('#modal').classList.add('hidden')}document.querySelector('#close').addEventListener('click',closeModal);document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});window.closeModal=closeModal;
