const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const items={battery:['🔋','Batería','Fuente'],solar:['☀️','Panel solar','Fuente'],switch:['🔘','Interruptor','Control'],lamp:['💡','Lámpara','Luz'],resistor:['〰️','Resistencia','Protección'],motor:['⚙️','Motor','Movimiento'],buzzer:['🔔','Timbre','Sonido'],fuse:['🧯','Fusible','Seguridad'],led:['🔴','LED','Luz']};let pieces=[],selectedCable='red',drag=null;const board=$('#board');
$('#parts').innerHTML=Object.entries(items).map(([k,v])=>`<button class="part" data-part="${k}"><span>${v[0]}</span><div><b>${v[1]}</b><small>${v[2]}</small></div></button>`).join('');
$$('.cable').forEach(b=>b.addEventListener('click',()=>{$$('.cable').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedCable=b.dataset.cable;$('#message').textContent='Cable '+b.dataset.cable+' seleccionado'}));$('.cable').classList.add('selected');
$$('.part').forEach(b=>b.addEventListener('click',()=>addPiece(b.dataset.part)));
function addPiece(type){pieces.push({type,x:35+(pieces.length%4)*145,y:35+(Math.floor(pieces.length/4)%3)*140});render();$('#message').textContent=items[type][1]+' agregado'}
function render(){if(!pieces.length){board.innerHTML='<svg id="wires"></svg><div id="empty">Elegí componentes del panel<br><small>Podés moverlos y usar cables infinitos</small></div>';return}board.innerHTML='<svg id="wires"></svg>'+pieces.map((p,i)=>`<div class="piece" data-i="${i}" style="left:${p.x}px;top:${p.y}px"><button class="remove" data-remove="${i}">×</button><span class="emoji">${items[p.type][0]}</span><b>${items[p.type][1]}</b><i class="terminal left"></i><i class="terminal right"></i></div>`).join('');drawWires();$$('.remove').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();pieces.splice(+x.dataset.remove,1);render()}));$$('.piece').forEach(el=>el.addEventListener('pointerdown',startDrag))}
function drawWires(){const svg=$('#wires');svg.innerHTML=pieces.slice(0,-1).map((p,i)=>{const n=pieces[i+1];return `<path class="cable-line ${selectedCable}" d="M${p.x+108} ${p.y+46} C${p.x+145} ${p.y+20},${n.x-35} ${n.y+72},${n.x} ${n.y+46}"/>`}).join('')}
function startDrag(e){if(e.target.classList.contains('remove'))return;const el=e.currentTarget,i=+el.dataset.i,sx=e.clientX,sy=e.clientY,ox=pieces[i].x,oy=pieces[i].y;el.setPointerCapture(e.pointerId);function move(ev){pieces[i].x=Math.max(5,ox+ev.clientX-sx);pieces[i].y=Math.max(5,oy+ev.clientY-sy);el.style.left=pieces[i].x+'px';el.style.top=pieces[i].y+'px';drawWires()}function stop(){el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',stop)}el.addEventListener('pointermove',move);el.addEventListener('pointerup',stop)}
$('#test').addEventListener('click',()=>{const has=x=>pieces.some(p=>p.type===x),load=has('lamp')||has('led')||has('motor')||has('buzzer');if(!has('battery')&&!has('solar'))return result('⚠ Falta una fuente de energía');if(!load)return result('🔴 CORTOCIRCUITO: agregá una lámpara, motor, LED o timbre');if(!has('switch'))return result('⚠ Agregá un interruptor para cerrar el circuito');$('#status').textContent='✓ Circuito funcionando';$('#status').style.color='#16a34a';$('#message').textContent='¡La corriente está circulando!';toast('Circuito correcto ⚡')});
$('#reset').addEventListener('click',()=>{pieces=[];render();$('#status').textContent='Circuito listo';$('#status').style.color=''});function result(t){$('#status').textContent=t;$('#status').style.color='#dc2626';toast(t)}function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}render();
