const components={battery:{name:'Batería',emoji:'🔋',desc:'Fuente de energía'},switch:{name:'Interruptor',emoji:'🔘',desc:'Abre o cierra el circuito'},lamp:{name:'Lámpara',emoji:'💡',desc:'Transforma energía en luz'},resistor:{name:'Resistencia',emoji:'〰️',desc:'Reduce la corriente'},motor:{name:'Motor',emoji:'⚙️',desc:'Transforma energía en movimiento'},buzzer:{name:'Timbre',emoji:'🔔',desc:'Produce sonido'},fuse:{name:'Fusible',emoji:'🧯',desc:'Protege el circuito'},solar:{name:'Panel solar',emoji:'☀️',desc:'Genera energía con luz'}};
const challenges=[['Circuito de luz','Encendé una lámpara con una batería','🔋 💡', ['battery','switch','lamp']],['Luz protegida','Usá una resistencia para cuidar la lámpara','🔋 〰️ 💡',['battery','switch','resistor','lamp']],['Motor eléctrico','Hacé girar un motor con un interruptor','🔋 ⚙️',['battery','switch','motor']],['Alarma','Activá un timbre sin provocar un corto','🔋 🔔',['battery','switch','buzzer']],['Energía solar','Encendé una lámpara usando el sol','☀️ 💡',['solar','switch','lamp']],['Protección total','Armá un circuito con fusible y resistencia','🔋 🧯 〰️ 💡',['battery','fuse','resistor','switch','lamp']]];
let mode='levels', current=null, placed=[], closed=false, points=0;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function renderChallenges(){ $('#challenges').innerHTML=challenges.map((c,i)=>`<article class="challenge ${i>0?'locked':''}" data-level="${i}"><div class="preview">${c[2]}</div><span class="number">DESAFÍO ${String(i+1).padStart(2,'0')}</span><h3>${c[0]}</h3><p>${c[1]}</p>${i===0?'<span class="badge">Disponible</span>':'<span class="badge" style="background:#f0f4f8;color:#718198">🔒 Próximamente</span>'}</article>`).join(''); $$('.challenge').forEach(x=>x.addEventListener('click',()=>{if(x.dataset.level==='0')openLab(challenges[0],0);else toast('Completá el desafío anterior para desbloquearlo')}))}
function renderInventory(){ $('#inventory').innerHTML=Object.entries(components).map(([key,c])=>`<button class="inv-btn" data-add="${key}"><span class="emoji">${c.emoji}</span><span><b>${c.name}</b><small>${c.desc}</small></span></button>`).join('');$$('.inv-btn').forEach(b=>b.addEventListener('click',()=>addPart(b.dataset.add)))}
function renderInfo(){ $('#component-grid').innerHTML=Object.values(components).map(c=>`<article class="info-card"><span class="emoji">${c.emoji}</span><h3>${c.name}</h3><p>${c.desc}. Aprendé a combinarlo con otras piezas en el modo libre.</p></article>`).join('')}
function showMode(m){mode=m;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));$$('.mode').forEach(x=>x.classList.add('hidden'));$('#'+m).classList.remove('hidden');if(m==='free')openLab(['Laboratorio libre','Experimentá con cualquier combinación','🧪',[]],-1);else $('#lab').classList.add('hidden')}
$$('.tab').forEach(t=>t.addEventListener('click',()=>showMode(t.dataset.mode)));
function openLab(c,i){current={...c,index:i};$('#levels').classList.add('hidden');$('#free').classList.add('hidden');$('#lab').classList.remove('hidden');$('#lab-title').textContent=c[0];$('#lab-subtitle').textContent=c[1];placed=[];closed=false;renderCircuit();setResult('neutral','Listo para probar');$('#explanation').textContent='💡 Consejo: todo circuito necesita una fuente de energía y un camino cerrado.';window.scrollTo({top:document.querySelector('#lab').offsetTop-20,behavior:'smooth'})}
function addPart(key){placed.push(key);renderCircuit();}
function removePart(i){placed.splice(i,1);renderCircuit()}
function renderCircuit(){const c=$('#circuit');c.classList.remove('live');if(!placed.length){c.innerHTML='<div id="empty" class="empty">Elegí componentes para empezar<br><span>Tu circuito aparecerá acá</span></div>';return}c.innerHTML=placed.map((key,i)=>`<div class="placed ${key}" data-i="${i}"><button class="x" data-remove="${i}">×</button><span>${components[key].emoji}</span><b>${components[key].name}</b></div>`).join('');$$('[data-remove]').forEach(x=>x.addEventListener('click',e=>{e.stopPropagation();removePart(+x.dataset.remove)}));}
function setResult(kind,text){$('#result').className='result '+kind;$('#result').textContent=text}
function testCircuit(){const has=k=>placed.includes(k), loads=['lamp','motor','buzzer'].some(has);if(!has('battery')&&!has('solar')){short('No hay fuente de energía. Agregá una batería o un panel solar.');return}if(has('battery')&&has('solar')){short('Dos fuentes enfrentadas: revisá cómo las conectaste.');return}if(!has('switch')){short('Falta un interruptor para controlar el circuito.');return}if(!closed){setResult('bad','⚠ Circuito abierto');$('#explanation').textContent='El interruptor está abierto: la corriente no puede recorrer todo el camino.';return}if(!loads){short('¡CORTOCIRCUITO! La corriente tiene un camino sin ningún componente que consuma energía.');return}if(has('lamp')&&has('motor')&&has('buzzer')&&!has('resistor')){short('¡Sobrecarga! Hay demasiados componentes conectados sin una resistencia.');return}$('#circuit').classList.add('live');$$('.placed.lamp,.placed.motor').forEach(x=>x.classList.add('on'));setResult('good','✓ Circuito funcionando');let text=has('resistor')?'La resistencia regula la corriente y protege los componentes. ¡Excelente combinación!':'¡La corriente recorrió el circuito y llegó a los componentes!';$('#explanation').textContent='🎉 '+text;if(current.index===0){points=100;$('#points').textContent=points;toast('Desafío completado: +100 puntos')}}
function short(msg){setResult('bad','⚠ Revisar circuito');$('#explanation').textContent='🔴 '+msg;$('#circuit').classList.remove('live');$$('.placed').forEach(x=>x.classList.remove('on'));toast(msg)}
$('#test').addEventListener('click',testCircuit);$('#switch').addEventListener('click',()=>{closed=!closed;$('#switch').textContent=closed?'Cerrar interruptor':'Abrir interruptor';$('#switch').style.background=closed?'#dcfce7':''});$('#clear').addEventListener('click',()=>openLab(['Laboratorio libre','Experimentá con cualquier combinación','🧪',[]],-1));$('#back').addEventListener('click',()=>{ $('#lab').classList.add('hidden');$('#levels').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})});$('#sound').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='🔊'?'🔇':'🔊'});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
renderChallenges();renderInventory();renderInfo();
